### ISSUE TITLE
Field getting initialized at build time with the "user.home" of the builder in native build

### ISSUE THREAD

**Issue by PierreBtz** [quarkiverse/quarkus-jgit#100]
While migrating an application to Quarkus 3.x, I noticed an issue with a field of a JGit class being initialized with a value it shouldn't have.

I managed to write a reproducer showing the issue in details: https://github.com/PierreBtz/quarkus-jgit-bug

# Details of the issue

After migrating my application (which is using jgit), I noticed the following stack on everyrun:

```
2023-09-06 17:55:23,829 ERROR Cannot save config file 'FileBasedConfig[/Users/elroy/.config/jgit/config]': java.io.IOException: Creating directories for /Users/<build_machine_user>/.config/jgit failed
	at org.eclipse.jgit.util.FileUtils.mkdirs(FileUtils.java:413)
	at org.eclipse.jgit.internal.storage.file.LockFile.lock(LockFile.java:140)
	at org.eclipse.jgit.storage.file.FileBasedConfig.save(FileBasedConfig.java:184)
	at org.eclipse.jgit.util.FS$FileStoreAttributes.saveToConfig(FS.java:766)
	at org.eclipse.jgit.util.FS$FileStoreAttributes.lambda$5(FS.java:448)
	at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)
```

Upon digging, I narrow the issue down to a jgit field being initialized at build time for no apparent reason (at least to me :)).

I'm not exactly sure about what's going on, but what is sure is that the [jgitConfig field](https://gerrit.googlesource.com/jgit/+/refs/heads/master/org.eclipse.jgit/src/org/eclipse/jgit/util/SystemReader.java#213) get initialized at build time when building the native binary.
My only explanation is that [this method](https://gerrit.googlesource.com/jgit/+/refs/heads/master/org.eclipse.jgit/src/org/eclipse/jgit/util/SystemReader.java#349) somehow gets evaluated at build time. I have been unable to explain why.

# How to reproduce

* Clone https://github.com/PierreBtz/quarkus-jgit-bug
* Build the native binary: `mvn package -Pnative`
* Execute the binary with a different user (no argument needed) and observe the output:

```
2023-09-06 17:38:37,605 INFO  [eu.pie.DemoCommand] (main) Value of the org.eclipse.jgit.util.SystemReader#jgitConfig field before any call to getJGitConfig: FileBasedConfig[/Users/<your_builder_user>/.config/jgit/config]
2023-09-06 17:38:37,605 INFO  [eu.pie.DemoCommand] (main) JGitConfig computed by calling openJGitConfig: FileBasedConfig[/Users/<your_current_user>/.config/jgit/config]
2023-09-06 17:38:37,606 INFO  [eu.pie.DemoCommand] (main) JGitConfig retrieved by calling getJGitConfig: FileBasedConfig[/Users/<your_builder_user>/.config/jgit/config]
```

Expectation would be to have something like:

```
2023-09-06 17:38:37,605 INFO  [eu.pie.DemoCommand] (main) Value of the org.eclipse.jgit.util.SystemReader#jgitConfig field before any call to getJGitConfig: FileBasedConfig[null]
2023-09-06 17:38:37,605 INFO  [eu.pie.DemoCommand] (main) JGitConfig computed by calling openJGitConfig: FileBasedConfig[/Users/<your_current_user>/.config/jgit/config]
2023-09-06 17:38:37,606 INFO  [eu.pie.DemoCommand] (main) JGitConfig retrieved by calling getJGitConfig: FileBasedConfig[/Users/<your_current_user>/.config/jgit/config]
```

* Environments this is reproduced on

* quarkus 3.3.2, 3.3.1, 3.0.3.Final
* quarkus-jgit 3.0.3 and 3.0.2
* graalvm 17.0.8+7.1 and graalvm 22.3.0 Java 17 CE

I tried to trace what's happening at build time but didn't have any luck :(
Let me know if you need more details.

**Comment by gastaldi** [comment]
@PierreBtz good catch! I managed to reproduce your issue in this PR: https://github.com/quarkiverse/quarkus-jgit/pull/101. 

I'll see what is missing. I remember fixing a similar issue in adf5acac24c51a1ddd5f0059f5872732ad813e45
