### ISSUE TITLE
Native Image Fails Cloning a Repository

### ISSUE THREAD

**Issue by kjq** [quarkiverse/quarkus-jgit#123]
When we build a native executable and go to clone a repository we get an error like this below.  We do not get this running as a JVM executable.

What is really odd is that it only happens on some repositories but at least in this case, the repository we are using always throws this exception.

```
[DEBUG] org.eclipse.jgit.internal.storage.file.FileSnapshot (executor-thread-1) file=/home/user/.gitconfig, is unmodified
[DEBUG] org.eclipse.jgit.internal.storage.file.FileSnapshot (executor-thread-1) file=/tmp/fusion13845187681936611258/.git/config.lock, isRacyClean=true, read=2024-06-07 23:30:11.618105000, lastModified=2024-06-07 23:30:11.597757539, delta=20347461 ns, racy<=2500000000 ns
[DEBUG] org.eclipse.jgit.internal.storage.file.FileSnapshot (executor-thread-1) file=/tmp/fusion13845187681936611258/.git/config.lock, is racily clean
[DEBUG] org.eclipse.jgit.internal.storage.file.FileSnapshot (executor-thread-1) file=/tmp/fusion13845187681936611258/.git/config, create new FileSnapshot: lastRead=2024-06-07 23:30:11.618503000, lastModified=2024-06-07 23:30:11.597757539, size=292, fileKey=(dev=840,ino=318944)
[DEBUG] org.eclipse.jgit.internal.storage.file.FileSnapshot (executor-thread-1) file=/tmp/fusion13845187681936611258/.git/config.lock, isRacyClean=true, read=2024-06-07 23:30:11.618503000, lastModified=2024-06-07 23:30:11.597757539, delta=20745461 ns, racy<=2500000000 ns
[DEBUG] org.eclipse.jgit.internal.util.ShutdownHook (executor-thread-1) unregister org.eclipse.jgit.internal.storage.file.LockFile$$Lambda/0x4f9f57f0c8d4e735841e0507671a3878f7e06cff0@36e6405f from shutdown hook
java.lang.NullPointerException
        at org.eclipse.jgit.internal.storage.file.WindowCache.evict(WindowCache.java:663)
        at org.eclipse.jgit.internal.storage.file.WindowCache.getOrLoad(WindowCache.java:623)
        at org.eclipse.jgit.internal.storage.file.WindowCache.get(WindowCache.java:387)
        at org.eclipse.jgit.internal.storage.file.WindowCursor.pin(WindowCursor.java:321)
        at org.eclipse.jgit.internal.storage.file.WindowCursor.inflate(WindowCursor.java:283)
        at org.eclipse.jgit.internal.storage.file.Pack.decompress(Pack.java:387)
        at org.eclipse.jgit.internal.storage.file.Pack.load(Pack.java:826)
        at org.eclipse.jgit.internal.storage.file.Pack.get(Pack.java:290)
        at org.eclipse.jgit.internal.storage.file.PackDirectory.open(PackDirectory.java:228)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedObject(ObjectDirectory.java:412)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedFromSelfOrAlternate(ObjectDirectory.java:375)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObjectWithoutRestoring(ObjectDirectory.java:365)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:350)
        at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:133)
        at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:216)
        at org.eclipse.jgit.dircache.Checkout.checkout(Checkout.java:168)
        at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:577)
        at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:480)
        at org.eclipse.jgit.api.CloneCommand.checkout(CloneCommand.java:393)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:214)
        at com.acme.workspace.WorkspaceResource.cloneTest2(WorkspaceResource.java:103)
        at com.acme.workspace.WorkspaceResource_Subclass.cloneTest2$$superforward(Unknown Source)
        at com.acme.workspace.WorkspaceResource_Subclass$$function$$11.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
        at io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:27)
        at io.quarkus.security.runtime.interceptor.AuthenticatedInterceptor.intercept(AuthenticatedInterceptor.java:29)
        at io.quarkus.security.runtime.interceptor.AuthenticatedInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor.intercept(StandardSecurityCheckInterceptor.java:44)
        at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor_AuthenticatedInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at com.acme.workspace.WorkspaceResource_Subclass.cloneTest2(Unknown Source)
        at com.acme.workspace.WorkspaceResource$quarkusrestinvoker$cloneTest2_ba751c24b903ee8ce930f0287b75b8c6bd9f755e.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:599)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
```

The call being made is just a test call but it looks like this:

```java
@GET
    @Path("/{client}/clone2")
    @Consumes(APPLICATION_JSON)
    @Produces(APPLICATION_JSON)
    public List<String> cloneTest2(final RepositoryRequest request, final @BeanParam ClientParams params) {
        System.setProperty("org.eclipse.jgit.util.Debug", "true");

        WindowCacheConfig cacheConfig = new WindowCacheConfig();
        cacheConfig.setPackedGitWindowSize(16 * 1024); // 16 KB
        cacheConfig.setPackedGitLimit(20 * 1024 * 1024); // 20 MB
        cacheConfig.setPackedGitOpenFiles(128);
        cacheConfig.setDeltaBaseCacheLimit(25 * 1024 * 1024); // 25 MB
        cacheConfig.install();

        Repository repo = new Repository();
        repo.setHost("https://[REPO-URL]");
        repo.setUsername("demo");
        repo.setPassword("[PAT]");

        File tmpDir;
        try {
            tmpDir = FileUtils.createTempFolder().toFile();
            CloneCommand cmd = Git.cloneRepository()
                .setDirectory(tmpDir)
                .setDepth(repo.getDepth())
                .setBranch(repo.getBranch())
                .setTimeout(5000)
                .setCloneAllBranches(false)
                .setURI(repo.toUrl());

            try (Git g = cmd.call()) {
                File[] files = tmpDir.listFiles();
                return Arrays.stream(files)
                    .map(File::getAbsolutePath)
                    .collect(Collectors.toList());
            }
        }
        catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        return null;
    }
```

**Comment by gastaldi** [comment]
Can you reproduce this error in a test in the `integration-tests` directory?

**Comment by kjq** [comment]
Here is a horrible reproducer but it demonstrates my exact issue when I use the actual repo I am targeting. The error is exactly the same.  When I run in JVM mode it works fine.

For the purpose of the reproducer I used the quarkus GitHub repo and the error it throws looks to similar to what I get except it is much more detailed/verbose... (running in JVM mode works)

**JVM Mode**
1. `mvn quarkus:dev`
2. Navigate to `http://localhost:8080/clone`
3. List of files returned

**Native Mode**
1. `mvn package -Pnative`
2. `cd /target`
3. `./code-with-quarkus-1.0.0-SNAPSHOT-runner`

**Comment by kjq** [comment]
What was weird is it didnt happen all the time except with this one repo.

**Comment by gastaldi** [comment]
@all-contributors add @kjq for bug

**Comment by kjq** [comment]
You need something to call out the Quarkus rockstars!  You guys are always the best!

**Comment by gastaldi** [comment]
@kjq I believe it's because the WindowCache didn't fill up in the other repositories. The error occurs when the `evict()` method is called

**Comment by kjq** [comment]
Thanks for looking at it so quickly! I really do appreciate it.

**Comment by gastaldi** [comment]
@kjq no problem, I was really intrigued about this error. Thanks for providing a reproducer and testing the patch :)

**Comment by gastaldi** [comment]
@kjq 3.1.1 is now out, have an excellent weekend 😉

**Comment by kjq** [comment]
I will now!  You too.

**Comment by kjq** [comment]
I love that with Quarkus it will take me 30 minutes to pull this in, test it, and release into prod!
